### ISSUE TITLE
Questions on NME in training 

### ISSUE THREAD

**Issue by wjtan99** [1adrianb/face-alignment-training#10]
I have two questions on NME in training 

1.  In your paper NME = 1/N * sum(|x-y||2 /d where d is the sqrt(w*h of the bounding box).  In your code, you use nn.MSECriterion.  Did you actually use the normalization by sqrt(w*h)?   If yes, can you point me to your lua code? 

2.   In your MSECriterion, you use the output in all 4 HG stacks and 4 repetition of labels (heat map of landmarks).  Is this a better way than only using MSE at the last stack?  

Thanks.

**Comment by 1adrianb** [comment]
1. Of course :) You are probably confusing the loss function with the way I computed the the error metrics. This repo contains only the trainign code. You can find it here: https://github.com/1adrianb/2D-and-3D-face-alignment/blob/fc4d29999a1f0b8a833805bfe437bd32df886242/utils.lua#L171

2. Yes, it is better to use all 4.

**Comment by wjtan99** [comment]
Thanks for your answers to both questions.  
Yes, I did confuse the two. It is clear to me now that you use NME in testing to measure the performance.
