### ISSUE TITLE
dataset-images.lua:16: attempt to index global 'opt' (a nil value)

### ISSUE THREAD

**Issue by ahuirecome** [1adrianb/face-alignment-training#13]
Well, I have been encounted with the following problem. It's strange and I couldn't figure out how to solve it. Would the code author or anyone else please help me?

Program starting as '"/opt/zbstudio/bin/linux/x64/lua" -e "io.stdout:setvbuf('no')" "/tmp/.nPlkeG"'.
Program 'lua' started in '/home/szh/project/github/face-alignment-training' (pid: 4261).
Debugging session started in '/home/szh/project/github/face-alignment-training/'.
=> Creating model from file: models/fan.lua
tput: No value for $TERM and no -T specified
=> Model size: 	23820176
=> Building dataset...
=> Dataset built. 57559 images were found.
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
/home/szh/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] ./dataset-images.lua:16: attempt to index global 'opt' (a nil value)
stack traceback:
	./dataset-images.lua:16: in function 'generateSampleFace'
	./dataset-images.lua:34: in function 'get'
	./dataloader.lua:87: in function <./dataloader.lua:81>
	[C]: in function 'xpcall'
	/home/szh/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
	/home/szh/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/szh/torch/install/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	/home/szh/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:15: in main chunk
stack traceback:
	[C]: in function 'error'
	/home/szh/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
	./dataloader.lua:123: in function '(for generator)'
	./train.lua:49: in function 'train'
	main.lua:41: in main chunk
Debugging session completed (traced 0 instructions).
Using lr_rate: 0.000250
=> Training epoch # 1
Program completed in 29.11 seconds (pid: 4261).

**Comment by 1adrianb** [comment]
@ahuirecome I forgot to add a self. in the code. Please check it now.

**Comment by ahuirecome** [comment]
@1adrianb thank you very much :)
