### ISSUE TITLE
I have a problem for caffe implementation

### ISSUE THREAD

**Issue by anshan-XR-ROB** [1adrianb/face-alignment-training#2]
Hi,
I have a problem for caffe implementation.
table.insert(out, tmpOut)
I want to know the meaning of this line. I only use tmpOut4 for output and the result is poor. Shoud l concat all tmpOut to output?

**Comment by 1adrianb** [comment]
Hi @AnshanTJU,

That particular line puts each intermediate output in a table which corresponds with the number of stacked modules  (in this case 4) . When training  you need to computer the loss against each of this intermediate outputs (so the loss is a linear combination of all them). When evaluating the last output should give you the best results.  Addionally it is possible that some implementations of the optimisation methods (ex: rmsprop) or intialisation may behave different between torch and caffe so you may need to adjust this to match the results during training.
