### ISSUE TITLE
Clarification of what 7% NME threshold means

### ISSUE THREAD

**Issue by davidparks21** [1adrianb/face-alignment-training#21]
Hi,
In going through your Face Alignment paper (excellent job by the way!), and I have a question. You define the NME and state that 7% NME from ground truth is the threshold used to classify a prediction as correct or incorrect. But I'm confused about what exactly 7% is. Since the NME metric is not on a [0, 1] scale. 

For an output of size 64x64 the maximum NME would be ~1.41 assuming the bounding box was 64x64 and the ground truth is the top left pixel and prediction is the bottom right pixel. 
sqrt( 64^2 + 64^2 ) / sqrt( 64 * 64 ) ~= 1.41

Did you normalize the NME to a [0, 1] scale first - e.g. 7% of 1.41? Or is the threshold simply 0.07 of the unscaled NME metric?

Thanks Adrian!
David

**Comment by 1adrianb** [comment]
HI @davidparks21,

Sorry for the confusion that we created in explaining this. The numbers reported are the AUC computed for NME<=7%. You can find the code used in https://github.com/1adrianb/2D-and-3D-face-alignment 

Thanks,
Adrian

**Comment by davidparks21** [comment]
Thanks for the quick response, and no problem, this was a minor detail in an otherwise brilliant paper. The code you referenced (copied below) clearly shows that you're using 0.07 as an absolute threshold value. That works quite well, and I understand what I'm reading perfectly now. Thanks!

```
axes1 = np.linspace(0,1,1000)
axes2 = np.zeros(1000)
print(errors.shape[0])
for i in range(1000):
    axes2[i] = (errors<axes1[i]).sum()/float(errors.shape[0])
plt.xlim(0,7)
plt.ylim(0,100)
plt.yticks(np.arange(0,110,10))
plt.xticks(np.arange(0,8,1))
plt.grid()
plt.title('NME (%)', fontsize=20)
plt.xlabel('NME (%)', fontsize=16)
plt.ylabel('Test Images (%)', fontsize=16)
plt.plot(axes1*100,axes2*100,'b-',label='FAN (Ours)',lw=3)
plt.legend(loc=4, fontsize=16)
plt.show()
print('AUC: ',np.sum(axes2[:70])/70)
```
