### ISSUE TITLE
How can I test my model in this repo?

### ISSUE THREAD

**Issue by samaonline** [1adrianb/face-alignment-training#3]
It seems when I test the model, it requires t7 file.

**Comment by 1adrianb** [comment]
Hi @samaonline,
This repo is only for training. You can test your trained model using this code: https://github.com/1adrianb/2D-and-3D-face-alignment 
Sorry for having them slipted like this,

**Comment by samaonline** [comment]
Thanks! Actually I changed the # of predicted key points from 68 to 6. Where can I modify in the test repo so that the architecture is the same as I used in training?

**Comment by 1adrianb** [comment]
Just replace all the reference of 68 to 6 in the project and modify the plot function to reflect the new number of points https://github.com/1adrianb/2D-and-3D-face-alignment/blob/fc4d29999a1f0b8a833805bfe437bd32df886242/utils.lua#L191
