### ISSUE TITLE
/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] ./dataset-images.lua:19: attempt to index global 'opt' (a nil value)

### ISSUE THREAD

**Issue by tjussh** [1adrianb/face-alignment-training#4]
## hi, 
when i run main.lua, I got the error, 

/home/tjussh/torch/install/bin/luajit: ...tjussh/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] ./dataset-images.lua:19: attempt to index global 'opt' (a nil value)
stack traceback:
	./dataset-images.lua:19: in function 'generateSampleFace'
	./dataset-images.lua:40: in function 'get'
	./dataloader.lua:107: in function <./dataloader.lua:101>
	[C]: in function 'xpcall'
	...tjussh/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
	...hua/torch/install/bin/../share/lua/5.1/threads/queue.lua:65: in function <...hua/torch/install/bin/../share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	...hua/torch/install/bin/../share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:15: in main chunk
stack traceback:
	[C]: in function 'error'
	...tjussh/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
	./dataloader.lua:145: in function '(for generator)'
	./train.lua:50: in function 'train'
	...a/Project/torch7/face-alignment-training-master/main.lua:44: in main chunk
	[C]: in function 'dofile'
	...ihua/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

any solutions? thank you very much.

**Comment by tjussh** [comment]
i just solved this problem. Thanks.

**Comment by CNDOTA** [comment]
I met the same problem, can you show your solution? Thank you!

**Comment by ChooJinHe** [comment]
Hi @tjussh I met the same problem too, may you show me your solution to it? Thanks a lot :D

**Comment by wind222** [comment]
Hi @tjussh I met the same problem too, may you show me your solution to it? Thanks a lot :D

**Comment by DanlanChen** [comment]
Hi @tjussh I met the same problem too, may you show me your solution to it? Thanks a lot :D
