### ISSUE TITLE
How can I  make my own dataset

### ISSUE THREAD

**Issue by PyJulie** [1adrianb/face-alignment-training#6]
I notice that the dataset you provided is .t7,How can I transform my own image to .t7?
for example,I have a image and mark every landmark by a (x,y)

**Comment by PyJulie** [comment]
and earnestly request that you provide a Python version? Thanks

**Comment by 1adrianb** [comment]
Hi @PyJulie in what format do you currently have your points? Torch can open .npy and .mat files with the help of some packages. So you can either modify the code to read mat/npy/txt files or use one of this packages to convert them to .t7
Ex: https://github.com/htwaijry/npy4th https://github.com/soumith/matio-ffi.torch

Regarding the python training code. I will add a python version, but this will happen somewhere toward the end of this month. Sorry for delay.

**Comment by PyJulie** [comment]
what about using the trianning code on other things,for example,train a model to draw a outline of a cow or a sheep？would it be suitable？

**Comment by 1adrianb** [comment]
@PyJulie yes, it should work for most of the fine-grained tasks (with some small tweaks here and there)
