### ISSUE TITLE
train my model

### ISSUE THREAD

**Issue by Jialeen** [1adrianb/face-alignment-training#9]
I want to train the face alignment model based on other face detection method, but I did not find the code to detect faces. Would you please give me some more information about this? Thank you very much.

**Comment by wjtan99** [comment]
This repo is for training only and it assumes there is a face in every image.  For face detection, refer to his python demo code at https://github.com/1adrianb/face-alignment.  It uses the dlib face detector.

**Comment by 1adrianb** [comment]
Hi @Jialeen, @wjtan99  is right. Plese do pay in mind that dlib doesnt work very well for faces found in large poses.

**Comment by Jialeen** [comment]
@wjtan99, @1adrianb, thank you very much. Maybe I did not make myself clear. My question is as follows:
      In my mind, the pipeline of training face alignment model is detecting faces firstly and then to train the face alignment model. And the trained model relies on the face detection method which means that we must employ the same face detection method in test phase.
      The open code to train model doesn't include face detection process. That is to say the face alignment model does not rely on the face detection, and we can use any face detection in test phase. Is this right? 
      Thank you very much.

**Comment by 1adrianb** [comment]
@Jialeen I just randomly perturbed the ground truth one. As long as your scale and position perturbations will account for the inaccuracy of your face detector you should be just fine. And yes, the code is not bounded to a particular face detector.
